export const LIST_NAME = [
  "Made Nita Cyntiani Ratnaningsih",
  "Made Widi Aryani",
  "Komang Yudi Arisandhi",
  "I Putu Satrya Buana",
  "Putu Indah Aprilya Pratiwi",
  "I Gusti Ketut Warjaya",
  "Pt. Ella Purnama Dewi",
  "Putu Darma Mahardipa",
  "I Komang Renata Christian Adiguna",
  "Ketut Ngurah Arya Krisna Satria Darma",
  "Kadek Surya Hadi Prawangsa",
  "Komang Tia Berliani",
  "Kadek Nova Wardana",
  "Putu Kumara Yasa",
  "Gede Etyana Witakusuma",
  "Komang Sri Wahyuni",
  "Kadek Pendy Wirata Kusuma",
  "Dwi Dharma Aditya",
  "Yeni Dwijayanti",
  "I Gede Gelgel Abdiutama",
  "Komang Bharata Suteja",
  "I Gede Herry Budikusuma",
  "I Kadek Ariadi Saputra",
  "Putu Arya Gunawan",
  "I Gede Tegeh Bagaskara",
  "Putu Diva Guna Prahasta",
  "Desak Putu Evayani",
  "Kadek Meita Cahya Ningsih",
  "Putu Fany Nadila Permata Sari",
  "I Gusti Putu Wahyu Pramanadika",
  "Kadek Dharma Yasa",
  "Dewa Putu Bayu Sastrawan",
  "Ida Ayu Putu Anggreni",
  "Michelle Natalie Putri",
  "Ketut Deri Mardana",
  "Gede Ryan Prasetya Gunawan",
  "Putu Rosy Agustini",
  "Ade Farrel Elkito Gunawan",
  "Muhammad Syafrizal Pratama",
  "Nuridin",
  "Luh Esa Suardani",
  "I Komang Ari Rediasa",
  "Putu Loji Putra Dermawan Ginantara.",
  "I Made Hendra Dwiguna Pawitra",
  "I Putu Yudisthira Putra Narmada",
  "Wiranata Negara",
  "Ketut Pingki Ardina",
  "Made Kelvin Pramudya Pinatih",
  "I Made Surya Atmaja",
  "Kadek Rahayu Cahyani",
  "I Putu Aryasa",
  "Kadek Desi Dhea Damayanthi",
  "Gede Andika Arya Pradita",
  "Putu Vysta Lucia Sri Antari",
  "Nurul Fatimah",
  "Made Bellisky Mahardhika",
  "Mahival Al Kautsar",
  "Ida Bagus Darma Utama",
  "I Ketut Rama Pradipta",
  "Ni Luh Ayu Mulyadi",
  "Kadek Sri Asih",
  "Aprileo Nanda Dwi Prakoso",
  "Putu Krisna Perdana",
  "Made Febri Hariadnyana",
];
